server:
  port                       : ${SEVER_PORT:8080}

keycloak:
  use-resource-role-mappings : true
  bearer-only                : true
  realm                      : ${REALM:Company}
  auth-server-url            : ${AUTH_SERVER:http://localhost:8083/auth}
  resource                   : ${AUTH_RESOURCE:department}
  credentials:
    secret                   : ${AUTH_SECRET:4aed3b70-d921-4bb3-8280-c8f0c3941103}
